### Register a new teacher
POST https://localhost:7297/api/auth/register
Content-Type: application/json

{
  "username": "johndoe4",
  "email": "johndoe4@example.com",
  "firstName": "John4",
  "lastName": "Doe4",
  "password": "password123"
}

### Login with the registered teacher
POST https://localhost:7297/api/auth/login
Content-Type: application/json

{
  "username": "johndoe4",
  "password": "password123"
}
